stages:
  - build

render_template:
  stage: build
  needs: [ ]
  tags:
    - linux
    - shell
  variables:
    GIT_DEPTH: 0
  script: 
    # TODO: Actually render out the template
    - cp pack_packer.template.yml pack_packer.yml
    # Fetch info about the current commit
    - VERSION="$(git --no-pager describe --tags --match 'v[0-9]*' | awk -F'-' '{ if (NF > 1) printf "%s.%s\n", $1, $2; else print $1 }')"
    - AUTHOR="$(git --no-pager show -s --format='%an <%ae>')"
    - MESSAGE="$(git --no-pager log -1 --pretty=%B)"
    # Evil git magic, to keep all files, but switch the branch
    - git fetch origin
    - git symbolic-ref HEAD refs/heads/compiled/latest
    - git reset
    # Create the commit and update the branches
    - git add pack_packer.yml
    - 'git commit --allow-empty --author="$AUTHOR" -m "$VERSION: $MESSAGE"'
    # Tag and mark all versions
    - git tag -a "compiled/$VERSION" -m "Version $VERSION" --force
    - git branch --force "compiled/${VERSION%.*}" HEAD
    - git branch --force "compiled/${VERSION%%.*}" HEAD
    # Push
    - git remote remove push_origin || true
    - git remote add push_origin "$CI_REPOSITORY_URL"
    - git push --all --follow-tags push_origin -o ci.skip
  except:
    - compiled/*
